/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend_with_auth.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Movie {
    id: MovieId;
    title: string;
    createdAt: bigint;
    year: bigint;
    description?: string;
    director: string;
    genre: Genre;
    watchStatus: WatchStatus;
    rating?: Rating;
}
export type MovieId = bigint;
export enum Genre {
    SciFi = "SciFi",
    Documentary = "Documentary",
    Action = "Action",
    Drama = "Drama",
    Romance = "Romance",
    Other = "Other",
    Animation = "Animation",
    Thriller = "Thriller",
    Comedy = "Comedy",
    Horror = "Horror"
}
export enum Rating {
    _1 = "_1",
    _2 = "_2",
    _3 = "_3",
    _4 = "_4",
    _5 = "_5"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WatchStatus {
    Unwatched = "Unwatched",
    Watchlist = "Watchlist",
    Watched = "Watched"
}
export interface backend_with_authInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMovie(title: string, year: bigint, genre: Genre, director: string, rating: Rating | null, description: string | null, watchStatus: WatchStatus): Promise<Movie>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteMovie(id: MovieId): Promise<void>;
    getAllMovies(): Promise<Array<Movie>>;
    getCallerUserRole(): Promise<UserRole>;
    getMovie(id: MovieId): Promise<Movie | null>;
    isCallerAdmin(): Promise<boolean>;
    updateMovie(id: MovieId, updatedMovie: Movie): Promise<Movie | null>;
}
import type { Genre as _Genre, Movie as _Movie, MovieId as _MovieId, Rating as _Rating, UserRole as _UserRole, WatchStatus as _WatchStatus } from "./declarations/backend_with_auth.did.d.ts";
export class Backend_with_auth implements backend_with_authInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMovie(arg0: string, arg1: bigint, arg2: Genre, arg3: string, arg4: Rating | null, arg5: string | null, arg6: WatchStatus): Promise<Movie> {
        if (this.processError) {
            try {
                const result = await this.actor.addMovie(arg0, arg1, to_candid_Genre_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_WatchStatus_n7(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Movie_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMovie(arg0, arg1, to_candid_Genre_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_WatchStatus_n7(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Movie_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteMovie(arg0: MovieId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMovie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMovie(arg0);
            return result;
        }
    }
    async getAllMovies(): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMovies();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMovies();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMovie(arg0: MovieId): Promise<Movie | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovie(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovie(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateMovie(arg0: MovieId, arg1: Movie): Promise<Movie | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMovie(arg0, to_candid_Movie_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMovie(arg0, to_candid_Movie_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Genre_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Movie_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Movie): Movie {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_WatchStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchStatus): WatchStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Rating]): Rating | null {
    return value.length === 0 ? null : from_candid_Rating_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Movie]): Movie | null {
    return value.length === 0 ? null : from_candid_Movie_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MovieId;
    title: string;
    createdAt: bigint;
    year: bigint;
    description: [] | [string];
    director: string;
    genre: _Genre;
    watchStatus: _WatchStatus;
    rating: [] | [_Rating];
}): {
    id: MovieId;
    title: string;
    createdAt: bigint;
    year: bigint;
    description?: string;
    director: string;
    genre: Genre;
    watchStatus: WatchStatus;
    rating?: Rating;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        year: value.year,
        description: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.description)),
        director: value.director,
        genre: from_candid_Genre_n12(_uploadFile, _downloadFile, value.genre),
        watchStatus: from_candid_WatchStatus_n14(_uploadFile, _downloadFile, value.watchStatus),
        rating: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rating))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SciFi: null;
} | {
    Documentary: null;
} | {
    Action: null;
} | {
    Drama: null;
} | {
    Romance: null;
} | {
    Other: null;
} | {
    Animation: null;
} | {
    Thriller: null;
} | {
    Comedy: null;
} | {
    Horror: null;
}): Genre {
    return "SciFi" in value ? Genre.SciFi : "Documentary" in value ? Genre.Documentary : "Action" in value ? Genre.Action : "Drama" in value ? Genre.Drama : "Romance" in value ? Genre.Romance : "Other" in value ? Genre.Other : "Animation" in value ? Genre.Animation : "Thriller" in value ? Genre.Thriller : "Comedy" in value ? Genre.Comedy : "Horror" in value ? Genre.Horror : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Unwatched: null;
} | {
    Watchlist: null;
} | {
    Watched: null;
}): WatchStatus {
    return "Unwatched" in value ? WatchStatus.Unwatched : "Watchlist" in value ? WatchStatus.Watchlist : "Watched" in value ? WatchStatus.Watched : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _1: null;
} | {
    _2: null;
} | {
    _3: null;
} | {
    _4: null;
} | {
    _5: null;
}): Rating {
    return "_1" in value ? Rating._1 : "_2" in value ? Rating._2 : "_3" in value ? Rating._3 : "_4" in value ? Rating._4 : "_5" in value ? Rating._5 : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Movie>): Array<Movie> {
    return value.map((x)=>from_candid_Movie_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Genre_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Movie_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Movie): _Movie {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Rating_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rating): _Rating {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_WatchStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchStatus): _WatchStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rating | null): [] | [_Rating] {
    return value === null ? candid_none() : candid_some(to_candid_Rating_n4(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: MovieId;
    title: string;
    createdAt: bigint;
    year: bigint;
    description?: string;
    director: string;
    genre: Genre;
    watchStatus: WatchStatus;
    rating?: Rating;
}): {
    id: _MovieId;
    title: string;
    createdAt: bigint;
    year: bigint;
    description: [] | [string];
    director: string;
    genre: _Genre;
    watchStatus: _WatchStatus;
    rating: [] | [_Rating];
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        year: value.year,
        description: value.description ? candid_some(value.description) : candid_none(),
        director: value.director,
        genre: to_candid_Genre_n1(_uploadFile, _downloadFile, value.genre),
        watchStatus: to_candid_WatchStatus_n7(_uploadFile, _downloadFile, value.watchStatus),
        rating: value.rating ? candid_some(to_candid_Rating_n4(_uploadFile, _downloadFile, value.rating)) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    SciFi: null;
} | {
    Documentary: null;
} | {
    Action: null;
} | {
    Drama: null;
} | {
    Romance: null;
} | {
    Other: null;
} | {
    Animation: null;
} | {
    Thriller: null;
} | {
    Comedy: null;
} | {
    Horror: null;
} {
    return value == Genre.SciFi ? {
        SciFi: null
    } : value == Genre.Documentary ? {
        Documentary: null
    } : value == Genre.Action ? {
        Action: null
    } : value == Genre.Drama ? {
        Drama: null
    } : value == Genre.Romance ? {
        Romance: null
    } : value == Genre.Other ? {
        Other: null
    } : value == Genre.Animation ? {
        Animation: null
    } : value == Genre.Thriller ? {
        Thriller: null
    } : value == Genre.Comedy ? {
        Comedy: null
    } : value == Genre.Horror ? {
        Horror: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rating): {
    _1: null;
} | {
    _2: null;
} | {
    _3: null;
} | {
    _4: null;
} | {
    _5: null;
} {
    return value == Rating._1 ? {
        _1: null
    } : value == Rating._2 ? {
        _2: null
    } : value == Rating._3 ? {
        _3: null
    } : value == Rating._4 ? {
        _4: null
    } : value == Rating._5 ? {
        _5: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchStatus): {
    Unwatched: null;
} | {
    Watchlist: null;
} | {
    Watched: null;
} {
    return value == WatchStatus.Unwatched ? {
        Unwatched: null
    } : value == WatchStatus.Watchlist ? {
        Watchlist: null
    } : value == WatchStatus.Watched ? {
        Watched: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend_with_auth {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend_with_auth(actor, _uploadFile, _downloadFile, options.processError);
}
