/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Genre = IDL.Variant({
  'SciFi' : IDL.Null,
  'Documentary' : IDL.Null,
  'Action' : IDL.Null,
  'Drama' : IDL.Null,
  'Romance' : IDL.Null,
  'Other' : IDL.Null,
  'Animation' : IDL.Null,
  'Thriller' : IDL.Null,
  'Comedy' : IDL.Null,
  'Horror' : IDL.Null,
});
export const Rating = IDL.Variant({
  '_1' : IDL.Null,
  '_2' : IDL.Null,
  '_3' : IDL.Null,
  '_4' : IDL.Null,
  '_5' : IDL.Null,
});
export const WatchStatus = IDL.Variant({
  'Unwatched' : IDL.Null,
  'Watchlist' : IDL.Null,
  'Watched' : IDL.Null,
});
export const MovieId = IDL.Nat;
export const Movie = IDL.Record({
  'id' : MovieId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'description' : IDL.Opt(IDL.Text),
  'director' : IDL.Text,
  'genre' : Genre,
  'watchStatus' : WatchStatus,
  'rating' : IDL.Opt(Rating),
});

export const idlService = IDL.Service({
  'addMovie' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        Genre,
        IDL.Text,
        IDL.Opt(Rating),
        IDL.Opt(IDL.Text),
        WatchStatus,
      ],
      [Movie],
      [],
    ),
  'deleteMovie' : IDL.Func([MovieId], [], []),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMovie' : IDL.Func([MovieId], [IDL.Opt(Movie)], ['query']),
  'updateMovie' : IDL.Func([MovieId, Movie], [IDL.Opt(Movie)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Genre = IDL.Variant({
    'SciFi' : IDL.Null,
    'Documentary' : IDL.Null,
    'Action' : IDL.Null,
    'Drama' : IDL.Null,
    'Romance' : IDL.Null,
    'Other' : IDL.Null,
    'Animation' : IDL.Null,
    'Thriller' : IDL.Null,
    'Comedy' : IDL.Null,
    'Horror' : IDL.Null,
  });
  const Rating = IDL.Variant({
    '_1' : IDL.Null,
    '_2' : IDL.Null,
    '_3' : IDL.Null,
    '_4' : IDL.Null,
    '_5' : IDL.Null,
  });
  const WatchStatus = IDL.Variant({
    'Unwatched' : IDL.Null,
    'Watchlist' : IDL.Null,
    'Watched' : IDL.Null,
  });
  const MovieId = IDL.Nat;
  const Movie = IDL.Record({
    'id' : MovieId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'description' : IDL.Opt(IDL.Text),
    'director' : IDL.Text,
    'genre' : Genre,
    'watchStatus' : WatchStatus,
    'rating' : IDL.Opt(Rating),
  });
  
  return IDL.Service({
    'addMovie' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          Genre,
          IDL.Text,
          IDL.Opt(Rating),
          IDL.Opt(IDL.Text),
          WatchStatus,
        ],
        [Movie],
        [],
      ),
    'deleteMovie' : IDL.Func([MovieId], [], []),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMovie' : IDL.Func([MovieId], [IDL.Opt(Movie)], ['query']),
    'updateMovie' : IDL.Func([MovieId, Movie], [IDL.Opt(Movie)], []),
  });
};

export const init = ({ IDL }) => { return []; };