/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Genre = { 'SciFi' : null } |
  { 'Documentary' : null } |
  { 'Action' : null } |
  { 'Drama' : null } |
  { 'Romance' : null } |
  { 'Other' : null } |
  { 'Animation' : null } |
  { 'Thriller' : null } |
  { 'Comedy' : null } |
  { 'Horror' : null };
export interface Movie {
  'id' : MovieId,
  'title' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'description' : [] | [string],
  'director' : string,
  'genre' : Genre,
  'watchStatus' : WatchStatus,
  'rating' : [] | [Rating],
}
export type MovieId = bigint;
export type Rating = { '_1' : null } |
  { '_2' : null } |
  { '_3' : null } |
  { '_4' : null } |
  { '_5' : null };
export type WatchStatus = { 'Unwatched' : null } |
  { 'Watchlist' : null } |
  { 'Watched' : null };
export interface _SERVICE {
  'addMovie' : ActorMethod<
    [string, bigint, Genre, string, [] | [Rating], [] | [string], WatchStatus],
    Movie
  >,
  'deleteMovie' : ActorMethod<[MovieId], undefined>,
  'getAllMovies' : ActorMethod<[], Array<Movie>>,
  'getMovie' : ActorMethod<[MovieId], [] | [Movie]>,
  'updateMovie' : ActorMethod<[MovieId, Movie], [] | [Movie]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];